# Generated by Django 3.2.8 on 2021-10-07 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('precio_uni', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('valor_total', models.IntegerField(default=0)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.producto')),
            ],
        ),
    ]
